<a href="https://colab.research.google.com/github/PallePrathyusha/deeplearning/blob/main/1st_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import tensorflow as tf
print("TF imported with eager execution!")
print("TF already imported with eager execution!")
odd = tf.constant([1,3,5,7,9,11,13,15,17,19,21,23], dtype=tf.int32)
print("odd:", odd)
ones = tf.ones([12], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(odd, ones)
print("just_beyond_odd:", just_beyond_odd)
twos = tf.constant([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = odd * twos
print("odd_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6],[7,8,9],[10,11,12]], dtype=tf.int32)
print(some_matrix)
some_matrix = tf.constant([[1, 2], [3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
TF already imported with eager execution!
odd: tf.Tensor([ 1  3  5  7  9 11 13 15 17 19 21 23], shape=(12,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1], shape=(12,), dtype=int32)
just_beyond_odd: tf.Tensor([ 2  4  6  8 10 12 14 16 18 20 22 24], shape=(12,), dtype=int32)
odd_doubled: tf.Tensor([ 2  6 10 14 18 22 26 30 34 38 42 46], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]], shape=(8, 2), dtype=int32)

value of some_matrix is:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
